New log file opened at Tue Oct 25 11:14:42 CEST 2016 by 16580@DESKTOP-093DMDB
Taking next connection to: 40591
New client attempting to connect on port: 40592-40591
  Address = /192.168.110.1:40591
This client on port 40592 has uuid 74fa64a0-66d3-48ce-90c4-339b6998e5be configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-74fa64a0-66d3-48ce-90c4-339b6998e5be
Taking next connection to: 40591
New client attempting to connect on port: 40593-40591
  Address = /192.168.110.1:40591
Handshake exception on socket: 40593
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 40591
New client attempting to connect on port: 40594-40591
  Address = /192.168.110.1:40591
This client on port 40594 has uuid 8560b788-ed20-45bd-a6ce-0b132d130db5 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-74fa64a0-66d3-48ce-90c4-339b6998e5be, activator-8560b788-ed20-45bd-a6ce-0b132d130db5
Taking next connection to: 40591
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 40591
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 40591
New client attempting to connect on port: 40619-40591
  Address = /192.168.110.1:40591
Handshake exception on socket: 40619
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 40591
New client attempting to connect on port: 40620-40591
  Address = /192.168.110.1:40591
This client on port 40620 has uuid 1b50f139-7d97-4fa9-ba54-bd51c151311e configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-8560b788-ed20-45bd-a6ce-0b132d130db5, play-fork-run-1b50f139-7d97-4fa9-ba54-bd51c151311e
Taking next connection to: 40591
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 40591
